cat > k8s/service.yaml <<'EOF'
apiVersion: v1
kind: Service
metadata:
  name: scart-service
spec:
  type: NodePort
  selector:
    app: scart
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
EOF
